#!/usr/bin/ruby

require "rubygems"

begin
  gem "ruby-mp3info"
rescue LoadError
  puts "Could not find gem \"ruby-mp3info\"\n"
  Process.exit
end

require "mp3info"

class String 
def remove_nonascii(replacement) 
n=self.split("") 
self.slice!(0..self.size) 
n.each{|b| 
 if b[0].to_i< 32 || b[0].to_i>127 || b[0].to_i == 34 then 
         self.concat(replacement) 
         else 
         self.concat(b) 
 end 
 } 
 self.to_s 
end 
end 

puts ARGV[0]
pathEndIdx = ARGV[0].rindex('/')
output_dir = ARGV[0].slice( 0, pathEndIdx )
puts output_dir

puts "Playlost Library Scanner\n"
autogen_file = File.new( output_dir + "/scripts/autogen_playlist.js", "w+" )


dir_base = Etc.getpwuid.dir + "/Music/"
if( dir_base.nil? )
  puts "Usage: library_scanner music_directory"
  Process.exit
end

mp3_filename_array = Array.new()

dir_array = Array.new()
dir_array << dir_base

dir_array.each{ |directory|
  puts "Directory: " + directory + "\n"
  Dir.chdir( directory )
  files = Dir.glob( "*" )

  files.each { | file |
	
	# Check if files is a directory
	if( File.directory?( file ) )
	  full_dir_path = directory + file + "/"
      puts "#{full_dir_path} is a directory\n"
	  dir_array << full_dir_path
    end
	
	# Check if file is an mp3
	filename_length = file.size
	if( filename_length >= 5 )
	  extension = file[ filename_length - 4, filename_length - 1 ]
	  if( extension == ".mp3" )
	    puts "#{file} is an mp3\n"
		mp3_filename_array << directory + file
	  end
	end
  }
}

# Randomize File Array
mp3_filename_array.length.each{ |idx|
  swap_idx = rand( mp3_filename_array.length - 1 )
  
  temp = mp3_filename_array[idx]
  mp3_filename_array[idx] = mp3_filename_array[swap_idx]
  mp3_filename_array[swap_idx] = temp
}

# Write to file
autogen_file.puts( "function Setup_Autogen_Song_Database()\n" )
autogen_file.puts( "{\n" );
autogen_file.puts( "this.list_length = #{mp3_filename_array.size};\n" )
autogen_file.puts( "this.list = new Array( this.list_length );\n" )

mp3_idx = 0;
mp3_filename_array.each{ |mp3_filename|
  puts "Trying: " + mp3_filename + "\n"
  
  mp3 = nil
  album = ""
  artist = ""
  title = ""
  filename = ""
  
  begin
    mp3 = Mp3Info.open( mp3_filename , :encoding => 'utf-8')
	album = mp3.tag.album
	artist = mp3.tag.artist
	title = mp3.tag.title
	filename = mp3_filename
  rescue
    puts "Song Error! Skipping"
  end

  puts "Title: #{title}\nArtist:#{artist}\nAlbum:#{album}\n\n\n"
  
  if album
	album = album.remove_nonascii( '-' )
  end
  if artist
	artist = artist.remove_nonascii( '-' )
  end
  if title
	title = title	.remove_nonascii( '-' )
  end
  
  autogen_file.puts( "this.list[#{mp3_idx}] = new Song( \"#{title}\", \"#{artist}\", \"#{filename}\" );\n" )
  
  mp3.close() if mp3
  
  mp3_idx += 1
}
autogen_file.puts( "}\n" )
autogen_file.close()